
'use server';
/**
 * @fileOverview Uses AI to suggest relevant document titles and detailed content based on a topic.
 *
 * - findExternalDocuments - A function that handles suggesting documents based on a topic.
 * - FindExternalDocumentsInput - The input type.
 * - FindExternalDocumentsOutput - The return type.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FindExternalDocumentsInputSchema = z.object({
  topic: z.string().describe('The topic to search documents for.'),
});
export type FindExternalDocumentsInput = z.infer<typeof FindExternalDocumentsInputSchema>;

const DocumentSearchResultSchema = z.object({
  id: z.string().describe("A unique ID for the search result"),
  title: z.string().describe("The title of the suggested document."),
  source: z.string().describe("The source type for the document."),
  simulatedTextContent: z.string().describe("Detailed text content generated by AI, summarizing the key information that this document would contain."),
});
export type DocumentSearchResult = z.infer<typeof DocumentSearchResultSchema>;

const FindExternalDocumentsOutputSchema = z.object({
  results: z.array(DocumentSearchResultSchema).describe("A list of AI-suggested document search results."),
  message: z.string().describe("A message to the user about the status or limitations of the search."),
});
export type FindExternalDocumentsOutput = z.infer<typeof FindExternalDocumentsOutputSchema>;

const AISuggestedDocumentSchema = z.object({
    title: z.string().describe("Título del documento, artículo académico o temario sugerido, específico y relevante al tema."),
    abstract: z.string().describe("Resumen detallado (3-5 frases) del contenido clave que cubriría este documento, incluyendo conceptos principales, temas y áreas de estudio.")
});

const AISuggestionOutputSchema = z.object({
    suggestions: z.array(AISuggestedDocumentSchema).describe("Lista de sugerencias de documentos relevantes al tema.")
});

const suggestDocumentsPrompt = ai.definePrompt({
    name: 'suggestDocumentsPrompt',
    input: { schema: FindExternalDocumentsInputSchema },
    output: { schema: AISuggestionOutputSchema },
    prompt: `Eres un asistente de investigación experto especializado en material de estudio y preparación de exámenes. Dado el tema "{{topic}}", sugiere entre 3 y 5 documentos, artículos académicos, temarios o guías de estudio altamente relevantes y específicos que serían extremadamente útiles para preparar un examen sobre este tema.

Para cada sugerencia, proporciona:
1. Un "title" específico y realista (como títulos de temarios oficiales, libros de texto reconocidos, o artículos académicos plausibles).
2. Un "abstract" detallado de 3 a 5 frases que describa los conceptos clave, temas y áreas de estudio que cubriría este documento. Este resumen debe ser lo suficientemente detallado como para servir como contenido de estudio por sí mismo.

Asegúrate de que:
- Los títulos y resúmenes estén en español.
- Cada sugerencia sea única y cubra un aspecto diferente del tema.
- El contenido sea específico al tema "{{topic}}" y no genérico.
- Los abstractos contengan información sustancial y útil para el estudio, no solo descripciones vagas.

Devuelve únicamente el objeto JSON con la clave "suggestions".
    `,
});


export async function findExternalDocuments(input: FindExternalDocumentsInput): Promise<FindExternalDocumentsOutput> {
  return findExternalDocumentsFlow(input);
}

const findExternalDocumentsFlow = ai.defineFlow(
  {
    name: 'findExternalDocumentsFlow',
    inputSchema: FindExternalDocumentsInputSchema,
    outputSchema: FindExternalDocumentsOutputSchema,
  },
  async (input) => {
    let message = "";
    let documentResults: DocumentSearchResult[] = [];

    try {
      const { output } = await suggestDocumentsPrompt(input);
      if (output && output.suggestions && output.suggestions.length > 0) {
        documentResults = output.suggestions.map((suggestion, index) => ({
          id: `ai_suggested_${Date.now()}_${index}`,
          title: suggestion.title,
          source: "Sugerido por IA",
          simulatedTextContent: suggestion.abstract
        }));
        message = `La IA ha sugerido ${documentResults.length} documentos relevantes para "${input.topic}". Selecciona los que quieras añadir para el análisis.`;
      } else {
        message = `La IA no pudo generar sugerencias específicas para "${input.topic}" en este momento. Puedes intentarlo de nuevo o con un tema diferente.`;
      }
    } catch (error) {
        console.error("Error calling AI for document suggestions:", error);
        message = "Error al contactar con la IA para sugerencias de documentos. Inténtalo de nuevo en unos momentos.";
    }

    if (documentResults.length === 0 && !message) {
         message = "No se encontraron documentos para este tema. Prueba con un tema más específico.";
    }

    return {
      results: documentResults,
      message: message,
    };
  }
);
